name: CI/CD Pipeline v1

on:
  workflow_dispatch:  # 只允许手动触发工作流
  # 或者你可以使用 push 和 workflow_dispatch 组合
  # push:
  #   branches:
  #     - main
  # workflow_dispatch:

permissions:
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_CONTAINER_APP_NAME: workflow
      AZURE_GROUP_NAME: workflow-resource-group
      AZURE_REGION: eastus
      IMAGE_NAME: ghcr.io/ocean-shine/workflow:latest
      AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
      AZURE_OPENAI_API_BASE: https://aiocean.openai.azure.com/
      AZURE_OPENAI_API_VERSION: "2024-08-01-preview"
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      GHCR_USERNAME: ocean-shine
      DOCKER_BUILD_REQUIRED: true  # 可以设置为 true 来构建镜像
      AZURE_CONTAINER_APP_ENV_NAME: workflow-env
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 安装 Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # 输出版本验证安装

      # 登录 GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # 如果需要构建 Docker 镜像
      - name: Build Docker Image
        if: ${{ env.DOCKER_BUILD_REQUIRED == 'true' }}
        run: |
          echo "Building Docker image..."
          docker build -t ${{ env.IMAGE_NAME }} .
          echo "Docker image built successfully."

      # 推送 Docker 镜像到 GHCR
      - name: Push Docker Image to GHCR
        if: ${{ env.DOCKER_BUILD_REQUIRED == 'true' }}
        run: |
          echo "Pushing Docker image to GHCR..."
          docker push ${{ env.IMAGE_NAME }}
          echo "Docker image pushed successfully."

      # 启动 Docker Compose 来运行 Qdrant 和 Uvicorn 容器
      - name: Start Docker Compose for Qdrant and Uvicorn
        run: |
          echo "Starting Docker Compose for Qdrant and Uvicorn..."
          # 使用已经创建好的 docker-compose.yml 文件启动服务
          docker-compose -f docker-compose.yml up -d
          echo "Docker Compose started successfully."
      

      # 部署到 Azure Container App
      - name: Deploy to Azure Container App
        run: |
          echo "Deploying Docker image to Azure Container App..."
          # 登录到 Azure CLI 使用 Service Principal
          echo "Logging into Azure..."
          az login --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}
          echo "Azure login successful."
          # 删除资源组（如果存在），并等待删除完成
          RESOURCE_GROUP_EXISTS=$(az group show --name ${{ env.AZURE_GROUP_NAME }} --query 'name' -o tsv 2>/dev/null || echo "NOT_FOUND")
          if [ "$RESOURCE_GROUP_EXISTS" != "NOT_FOUND" ]; then
            echo "Resource Group exists, deleting: ${{ env.AZURE_GROUP_NAME }}"
            az group delete --name ${{ env.AZURE_GROUP_NAME }} --yes --no-wait
            echo "Resource Group deletion started. Waiting for it to be deleted..."
            # 等待资源组删除完成
            until ! az group show --name ${{ env.AZURE_GROUP_NAME }} --query 'name' -o tsv 2>/dev/null; do
              echo "Resource group still exists. Waiting for 1 minute..."
              sleep 60
            done
            echo "Resource group deleted successfully."
          else
            echo "Resource group does not exist, skipping deletion."
          fi
          # 删除容器应用环境（如果存在），并等待删除完成
          ENV_EXISTS=$(az containerapp env show --name ${{ env.AZURE_CONTAINER_APP_ENV_NAME }} --resource-group ${{ env.AZURE_GROUP_NAME }} --query 'name' -o tsv 2>/dev/null || echo "NOT_FOUND")
          
          if [ "$ENV_EXISTS" != "NOT_FOUND" ]; then
            echo "Container App environment exists, deleting: ${{ env.AZURE_CONTAINER_APP_ENV_NAME }}"
            az containerapp env delete --name ${{ env.AZURE_CONTAINER_APP_ENV_NAME }} --resource-group ${{ env.AZURE_GROUP_NAME }} --yes --no-wait
            echo "Container App environment deletion started. Waiting for it to be deleted..."
            # 等待容器应用环境删除完成
            until ! az containerapp env show --name ${{ env.AZURE_CONTAINER_APP_ENV_NAME }} --resource-group ${{ env.AZURE_GROUP_NAME }} --query 'name' -o tsv 2>/dev/null; do
              echo "Container app environment still exists. Waiting for 1 minute..."
              sleep 60
            done
            echo "Container app environment deleted successfully."
          else
            echo "Container app environment does not exist, skipping deletion."
          fi
          # 删除容器应用（如果存在），并等待删除完成
          APP_EXISTS=$(az containerapp show --name ${{ env.AZURE_CONTAINER_APP_NAME }} --resource-group ${{ env.AZURE_GROUP_NAME }} --query 'name' -o tsv 2>/dev/null || echo "NOT_FOUND")
          
          if [ "$APP_EXISTS" != "NOT_FOUND" ]; then
            echo "Container app exists, deleting: ${{ env.AZURE_CONTAINER_APP_NAME }}"
            az containerapp delete --name ${{ env.AZURE_CONTAINER_APP_NAME }} --resource-group ${{ env.AZURE_GROUP_NAME }} --yes --no-wait
            echo "Container app deletion started. Waiting for it to be deleted..."
            # 等待容器应用删除完成
            until ! az containerapp show --name ${{ env.AZURE_CONTAINER_APP_NAME }} --resource-group ${{ env.AZURE_GROUP_NAME }} --query 'name' -o tsv 2>/dev/null; do
              echo "Container app still exists. Waiting for 1 minute..."
              sleep 60
            done
            echo "Container app deleted successfully."
          else
            echo "Container app does not exist, skipping deletion."
          fi
          # 确认资源删除完成后，重新创建资源组
          echo "Creating Resource Group: ${{ env.AZURE_GROUP_NAME }}"
          az group create --name ${{ env.AZURE_GROUP_NAME }} --location ${{ env.AZURE_REGION }}
          echo "Resource group created successfully."
          # 重新创建容器应用环境
          echo "Creating Container App Environment: ${{ env.AZURE_CONTAINER_APP_ENV_NAME }}"
          az containerapp env create \
            --name ${{ env.AZURE_CONTAINER_APP_ENV_NAME }} \
            --resource-group ${{ env.AZURE_GROUP_NAME }} \
            --location ${{ env.AZURE_REGION }}
          echo "Container App environment created successfully."
          # 重新创建容器应用
          echo "Creating Container App: ${{ env.AZURE_CONTAINER_APP_NAME }}"
          az containerapp create \
            --name ${{ env.AZURE_CONTAINER_APP_NAME }} \
            --resource-group ${{ env.AZURE_GROUP_NAME }} \
            --cpu 2 --memory 4Gi \
            --env-vars AZURE_OPENAI_API_KEY=${{ secrets.AZURE_OPENAI_API_KEY }} AZURE_OPENAI_API_BASE=${{ env.AZURE_OPENAI_API_BASE }} AZURE_OPENAI_API_VERSION=${{ env.AZURE_OPENAI_API_VERSION }} \
            --ingress external --target-port 80 --environment ${{ env.AZURE_CONTAINER_APP_ENV_NAME }} \
            --image ${{ env.IMAGE_NAME }} \
            --registry-server ghcr.io \
            --registry-username ${{ env.GHCR_USERNAME }} \
            --registry-password ${{ secrets.GHCR_TOKEN }}
          echo "Azure Container App deployment complete!"
