name: CI/CD Pipeline v3

on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_CONTAINER_APP_NAME: workflow
      AZURE_GROUP_NAME: workflow-resource-group
      AZURE_REGION: eastus
      IMAGE_NAME: ghcr.io/ocean-shine/workflow:latest
      OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
      OPENAI_API_BASE: https://aiocean.openai.azure.com/
      OPENAI_API_VERSION: "2024-08-01-preview"
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      DOCKER_BUILD_REQUIRED: false  # 可以设置为 true 来构建镜像
      AZURE_CONTAINER_APP_ENV_NAME: workflow-env
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 登录 GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # 如果需要构建 Docker 镜像
      - name: Build Docker Image
        if: ${{ env.DOCKER_BUILD_REQUIRED == 'true' }}
        run: |
          echo "Building Docker image..."
          docker build -t ${{ env.IMAGE_NAME }} .
          echo "Docker image built successfully."

      # 推送 Docker 镜像到 GHCR
      - name: Push Docker Image to GHCR
        if: ${{ env.DOCKER_BUILD_REQUIRED == 'true' }}
        run: |
          echo "Pushing Docker image to GHCR..."
          docker push ${{ env.IMAGE_NAME }}
          echo "Docker image pushed successfully."

      - name: Deploy to Azure Container App
        run: |
          echo "Deploying Docker image to Azure Container App..."

          # 登录到 Azure CLI 使用 Service Principal
          echo "Logging into Azure..."
          az login --service-principal \
            --username ${{ secrets.AZURE_CLIENT_ID }} \
            --password ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}
          echo "Azure login successful."

          # 检查资源组是否存在
          RESOURCE_GROUP_EXISTS=$(az group show --name ${{ env.AZURE_GROUP_NAME }} --query 'name' -o tsv 2>/dev/null || echo "NOT_FOUND")
          if [ "$RESOURCE_GROUP_EXISTS" != "NOT_FOUND" ]; then
            echo "Resource Group exists, skipping deletion."
          else
            echo "Resource Group does not exist, creating: ${{ env.AZURE_GROUP_NAME }}"
            az group create --name ${{ env.AZURE_GROUP_NAME }} --location ${{ env.AZURE_REGION }}
            echo "Resource group created successfully."
          fi

          # 检查容器应用环境是否存在
          ENV_EXISTS=$(az containerapp env show --name ${{ env.AZURE_CONTAINER_APP_ENV_NAME }} --resource-group ${{ env.AZURE_GROUP_NAME }} --query 'name' -o tsv 2>/dev/null || echo "NOT_FOUND")

          if [ "$ENV_EXISTS" != "NOT_FOUND" ]; then
            echo "Container App environment exists, skipping creation."
          else
            echo "Container App environment does not exist, creating: ${{ env.AZURE_CONTAINER_APP_ENV_NAME }}"
            az containerapp env create \
              --name ${{ env.AZURE_CONTAINER_APP_ENV_NAME }} \
              --resource-group ${{ env.AZURE_GROUP_NAME }} \
              --location ${{ env.AZURE_REGION }}
            echo "Container App environment created successfully."
          fi

          # 检查容器应用是否存在
          APP_EXISTS=$(az containerapp show --name ${{ env.AZURE_CONTAINER_APP_NAME }} --resource-group ${{ env.AZURE_GROUP_NAME }} --query 'name' -o tsv 2>/dev/null || echo "NOT_FOUND")

          if [ "$APP_EXISTS" != "NOT_FOUND" ]; then
            echo "Container app exists, deleting existing app: ${{ env.AZURE_CONTAINER_APP_NAME }}"
            az containerapp delete --name ${{ env.AZURE_CONTAINER_APP_NAME }} --resource-group ${{ env.AZURE_GROUP_NAME }} --yes --no-wait
            echo "Container app deletion started. Waiting for it to be deleted..."
            
            # 等待删除容器应用
            until ! az containerapp show --name ${{ env.AZURE_CONTAINER_APP_NAME }} --resource-group ${{ env.AZURE_GROUP_NAME }} --query 'name' -o tsv 2>/dev/null; do
              echo "Container app still exists. Waiting for 1 minute..."
              sleep 60
            done
            echo "Container app deleted successfully."
          else
            echo "Container app does not exist, skipping deletion."
          fi

          # 创建容器应用
          echo "Creating new Azure Container App: ${{ env.AZURE_CONTAINER_APP_NAME }}"
          az containerapp create \
            --name ${{ env.AZURE_CONTAINER_APP_NAME }} \
            --resource-group ${{ env.AZURE_GROUP_NAME }} \
            --cpu 1 --memory 2Gi \
            --env-vars OPENAI_API_KEY=${{ env.OPENAI_API_KEY }} OPENAI_API_BASE=${{ env.OPENAI_API_BASE }} OPENAI_API_VERSION=${{ env.OPENAI_API_VERSION }} \
            --ingress external --target-port 80 --environment ${{ env.AZURE_CONTAINER_APP_ENV_NAME }} \
            --image ${{ env.IMAGE_NAME }} \
            --registry-username ${{ secrets.GHCR_USERNAME }} \
            --registry-password ${{ secrets.GHCR_TOKEN }}

          echo "Azure Container App deployment complete!"
